In [26]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')


In [27]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0                     grantland.com        0        0           1          2   
1  waylandplanninganddevelopment.uk        0        0           1          2   
2                     getpocket.com        0        0           1          1   
3                        tobogo.net        0        0           1          2   
4                     bimsalasim.de        0        0           1          4   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  \
0            0             0        0              0           0            1   
1            0             0        0              0           0            1   
2            1             0        1              0           0            1   
3            0             0        0              0           0            1   
4            0             0        0              0           0            0   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           1           1       0           0            1             0   
1           0           1       0           0            1             0   
2           0           1       0           0            1             0   
3           0           0       0           0            1             0   
4           1           1       0           0            1             0   

   Label  
0      0  
1      1  
2      0  
3      0  
4      1

In [28]:
X = data.drop(['Domain', 'Label'], axis=1)

In [29]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          2            0             0   
1        0        0           1          2            0             0   
2        0        0           1          1            1             0   
3        0        0           1          2            0             0   
4        0        0           1          4            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            1           1           1   
1        0              0           0            1           0           1   
2        1              0           0            1           0           1   
3        0              0           0            1           0           0   
4        0              0           0            0           1           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [30]:
y=np.ravel(data['Label'])
#y=np.ravel(data['Outcome'])

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [32]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [33]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [34]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.8053333333333333
Precision: 0.8269576806066604
Recall: 0.8053333333333333
F1 Score: 0.8014663139222397
Confusion Matrix:
[[1431   96]
 [ 488  985]]

SVC Metrics:
Accuracy: 0.8323333333333334
Precision: 0.8616355490247206
Recall: 0.8323333333333334
F1 Score: 0.8283345767575323
Confusion Matrix:
[[1491   36]
 [ 467 1006]]

RandomForestClassifier Metrics:
Accuracy: 0.8593333333333333
Precision: 0.8651425717088135
Recall: 0.8593333333333333
F1 Score: 0.8585761864188337
Confusion Matrix:
[[1413  114]
 [ 308 1165]]

MLPClassifier Metrics:
Accuracy: 0.8443333333333334
Precision: 0.8496722570416204
Recall: 0.8443333333333334
F1 Score: 0.8435185187878042
Confusion Matrix:
[[1389  138]
 [ 329 1144]]

KNeighborsClassifier Metrics:
Accuracy: 0.84
Precision: 0.8446387401677546
Recall: 0.84
F1 Score: 0.8392466164142642
Confusion Matrix:
[[1377  150]
 [ 330 1143]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8576666666666667
Precision: 0.8637601927124358
Recal

In [35]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.859333   0.865143  0.859333  0.858576
5  DecisionTreeClassifier  0.857667   0.863760  0.857667  0.856865
3           MLPClassifier  0.844333   0.849672  0.844333  0.843519
4    KNeighborsClassifier  0.840000   0.844639  0.840000  0.839247
1                     SVC  0.832333   0.861636  0.832333  0.828335
0      LogisticRegression  0.805333   0.826958  0.805333  0.801466
